config/routes.rb
class MainSite 
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do |map|
  # Routes for the public site
  constraints MainSite do
    # Homepage
    root :to => "content#index"
    map.connect  '/home', :controller=>'home', :action=>'index'
    map.connect '/pages/:id', :controller=>'blog', :action=>'page'
   map.connect '/contacts', :controller=>'blog', :action=>'contact'
   
    # Account Signup Routes
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
   
    match '/signin' => 'presessions#new', :as => 'signin' 
    match '/preauthenticate' => 'presessions#create', :as => 'preauthentication'
    
    # Catch-all that just loads views from app/views/content/* ...
    # e.g, http://yoursite.com/content/about -> app/views/content/about.html.erb
    #
    match '/content/:action' => 'content'
  end

  root :to => "songs#index"

  devise_for :users

  #
  # Account / User Management Routes
  #
  resources :users
  
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match :billing, :paypal, :plan, :plan_paypal, :cancel
    end
   resources :pages
  end

  # Custom routes specific to our app
  namespace "saas_admin" do
    resources :pages do
      put "reposition", :on => :member
    end
    
    resources :posts
    resources :songs
    resources :messages
  end

  resources :pages, :only => :show
  resources :posts, :only => [ :index, :show ]
  match     "playlist" => "songs#index"
  post      "songs/flag" => "songs#flag",     :as => "flag"

  get    "contact"      => "messages#new",    :as => "contact"
  post   "/home" => "messages#create", :as => "deliver"
  get    "contact/sent" => "messages#sent",   :as => "sent"


end

app/models/post.rb
class Post < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 10

  attr_accessible :title, :body

  validates :title, :presence => true

  def body_html
    RDiscount.new(body || "").to_html
  end

  def to_param
    slug = title.downcase
    slug.gsub!(/\W/, "-")    # Replace each non-letter, non-digit, and non-underscore with a dash
    slug.gsub!(/-{2,}/, "-") # Replace sequences of dashes with a single dash
    slug.gsub!(/-\z/, "")    # Strip trailing slash
    "#{id}-#{slug}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def index
    @posts = Post.paginate :page => params[:page], :order => "created_at DESC"
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/saas_admin/contacts_controller.rb
class SaasAdmin::ContactsController < ApplicationController
end

app/controllers/saas_admin/pages_controller.rb
class SaasAdmin::PagesController < ApplicationController
  include Saas::ControllerHelpers
  uses_tiny_mce

  def create
    @page = Page.new(params[:page])
    @page.position = (Page.maximum(:position) || 0) + 1
    create!
  end

  def update
    update! { edit_saas_admin_page_url(@page) }
  end
  
  def reposition
    @page = Page.find(params[:id])
    
    respond_to do |format|
      if @page.insert_at(params[:position])
        format.js { head :ok }
      else
        format.js { head :unprocessable_entity } # Maybe find a better status code to use.
      end
    end
  end
end

app/controllers/saas_admin/posts_controller.rb
class SaasAdmin::PostsController < ApplicationController
  include Saas::ControllerHelpers
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/saas_admin/contacts_helper.rb
module SaasAdmin::ContactsHelper
end

app/helpers/saas_admin/dashboard_helper.rb
module SaasAdmin::DashboardHelper
end

app/helpers/saas_admin/pages_helper.rb
module SaasAdmin::PagesHelper
end

app/helpers/saas_admin/posts_helper.rb
module SaasAdmin::PostsHelper
end

app/views/saas_admin/posts/_form.html.erb
<%= f.error_messages %>

<p>
  <%= link_to "Formatting guide", "http://daringfireball.net/projects/markdown/syntax", :target => "_blank" %>
</p>

<div class="field string">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="field text">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<%= submit_or_cancel %>

app/views/saas_admin/posts/_post.html.erb
<div class="post">
  <h2><%= link_to post.title, post_url(post, :subdomain => false) %></h2>
  <time datetime="<%= post.created_at.to_s(:db).split(" ").first %>"><%= post.created_at.to_s(:short_day) %></time>

  <%= post.body_html.html_safe %>
</div>

app/views/saas_admin/posts/edit.html.erb
<h2><%= @page_title = "Edit Blog Post" %></h2>

<%= form_for [:saas_admin, @post] do |f| -%>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end -%>

app/views/saas_admin/posts/index.html.erb
<h2><%= @page_title = "Blog Posts" %></h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, saas_admin_post_path(post) %></td>
        <td><%= post.created_at.to_s(:short_day) %></td>
        <td>
          <%= link_to "Edit", edit_saas_admin_post_path(post) %>
          <%= link_to "Delete", saas_admin_post_path(post), :method => :delete, :confirm => "Are you sure you want to permanently delete this post?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create a new post", new_saas_admin_post_path %>

app/views/saas_admin/posts/new.html.erb
<h2><%= @page_title = "Create Blog Post" %></h2>

<%= form_for [:saas_admin, @post] do |f| -%>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end -%>

app/views/saas_admin/posts/show.html.erb
<%= render :partial => "post", :locals => { :post => @post } %>