config/routes.rb
class MainSite 
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do |map|
  # Routes for the public site
  constraints MainSite do
    # Homepage
    root :to => "content#index"
    map.connect  '/home', :controller=>'home', :action=>'index'
    map.connect '/pages/:id', :controller=>'blog', :action=>'page'
   map.connect '/contacts', :controller=>'blog', :action=>'contact'
   
    # Account Signup Routes
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
   
    match '/signin' => 'presessions#new', :as => 'signin' 
    match '/preauthenticate' => 'presessions#create', :as => 'preauthentication'
    
    # Catch-all that just loads views from app/views/content/* ...
    # e.g, http://yoursite.com/content/about -> app/views/content/about.html.erb
    #
    match '/content/:action' => 'content'
  end

  root :to => "songs#index"

  devise_for :users

  #
  # Account / User Management Routes
  #
  resources :users
  
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match :billing, :paypal, :plan, :plan_paypal, :cancel
    end
   resources :pages
  end

  # Custom routes specific to our app
  namespace "saas_admin" do
    resources :pages do
      put "reposition", :on => :member
    end
    
    resources :posts
    resources :songs
    resources :messages
  end

  resources :pages, :only => :show
  resources :posts, :only => [ :index, :show ]
  match     "playlist" => "songs#index"
  post      "songs/flag" => "songs#flag",     :as => "flag"

  get    "contact"      => "messages#new",    :as => "contact"
  post   "/home" => "messages#create", :as => "deliver"
  get    "contact/sent" => "messages#sent",   :as => "sent"


end

app/models/song.rb
class Song < ActiveRecord::Base
  GENRES = ["Rock", "Hardcore Rock", "R&B/Hip-Hop", "Country", "Electric"]
  
  has_many :flags, :dependent => :destroy
  has_many :accounts, :through => :flags
  
  default_scope order("genre ASC, title ASC")
  
  attr_accessible :url, :title, :video_id, :seconds, :genre, :explicit

  before_validation :populate_fields

  validates :title,    :presence => true
  validates :video_id, :presence => true, :uniqueness => true
  validates :seconds,  :presence => true, :numericality => true
  validates :genre, :presence => true, :inclusion => { :in => GENRES }
  
  scope :not_flagged_by_account, lambda { |user|
      Song.where(Song.arel_table[:id].not_in(Flag.arel_table.project(:song_id).where(Flag.arel_table[:account_id].eq(user.account.id))))
  }
  scope :clean, where(:explicit => false)

  def url=(new_url)
    self.video_id = (a = new_url["?v="]) ? new_url.split("?v=")[1] : new_url.split("/")[-1]
  end

  def url
    video_id ? "http://www.youtube.com/watch?v=#{video_id}" : nil
  end

  protected

  def populate_fields
    if video_id && video_id_changed?
      response = HTTParty.get("http://gdata.youtube.com/feeds/api/videos/#{video_id}?v=2")

      if response.response.code == "200"
        feed = Nokogiri::XML.parse(response.body)
        self.title = feed.xpath("//media:title").text
        self.seconds = feed.xpath("//yt:duration").attribute("seconds").value
        self.flags.each do |flag|
          flag.destroy
        end
      else
        errors[:base] << "Data for this video isn't available yet. Try again in an hour or two."
      end
    end
  end
end

app/controllers/saas_admin/contacts_controller.rb
class SaasAdmin::ContactsController < ApplicationController
end

app/controllers/saas_admin/pages_controller.rb
class SaasAdmin::PagesController < ApplicationController
  include Saas::ControllerHelpers
  uses_tiny_mce

  def create
    @page = Page.new(params[:page])
    @page.position = (Page.maximum(:position) || 0) + 1
    create!
  end

  def update
    update! { edit_saas_admin_page_url(@page) }
  end
  
  def reposition
    @page = Page.find(params[:id])
    
    respond_to do |format|
      if @page.insert_at(params[:position])
        format.js { head :ok }
      else
        format.js { head :unprocessable_entity } # Maybe find a better status code to use.
      end
    end
  end
end

app/controllers/saas_admin/posts_controller.rb
class SaasAdmin::PostsController < ApplicationController
  include Saas::ControllerHelpers
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
end

app/helpers/saas_admin/contacts_helper.rb
module SaasAdmin::ContactsHelper
end

app/helpers/saas_admin/dashboard_helper.rb
module SaasAdmin::DashboardHelper
end

app/helpers/saas_admin/pages_helper.rb
module SaasAdmin::PagesHelper
end

app/helpers/saas_admin/posts_helper.rb
module SaasAdmin::PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/saas_admin/songs/_form.html.erb
<%= f.error_messages %>

<div class="field string">
  <%= f.label :url, "What's the song's URL?" %>
  <%= f.text_field :url %>
</div>

<div class="field string">
  <%= f.label :genre %>
  <%= f.select :genre, Song::GENRES %>
</div>

<div class="field boolean">
  <%= f.label :explicit %>
  <%= f.check_box :explicit %>
</div>

<% unless @song.new_record? %>
  <div class="field string">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
<% end %>

<%= submit_or_cancel %>

app/views/saas_admin/songs/edit.html.erb
<h2><%= @page_title = "Edit Song" %></h2>

<%= form_for [:saas_admin, @song] do |f| -%>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end -%>

app/views/saas_admin/songs/index.html.erb
<h2><%= @page_title = "Songs" %></h2>

<%= link_to "Add a new song", new_saas_admin_song_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Explicit</th>
      <th>Flags</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.genre %></td>
        <td><%= song.explicit ? "Yes" : "No" %></td>
        <td><%= song.flags.count %></td>
        <td>
          <%= link_to "Edit", edit_saas_admin_song_path(song) %>
          <%= link_to "Delete", saas_admin_song_path(song), :method => :delete, :confirm => "Are you sure you want to permanently delete this song?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add a new song", new_saas_admin_song_path %>

app/views/saas_admin/songs/new.html.erb
<h2><%= @page_title = "Add Song" %></h2>

<%= form_for [:saas_admin, @song] do |f| -%>
  <%= render :partial => "form", :locals => { :f => f } %>
<% end -%>