config/routes.rb
class MainSite 
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do |map|
  # Routes for the public site
  constraints MainSite do
    # Homepage
    root :to => "content#index"
    map.connect  '/home', :controller=>'home', :action=>'index'
    map.connect '/pages/:id', :controller=>'blog', :action=>'page'
   map.connect '/contacts', :controller=>'blog', :action=>'contact'
   
    # Account Signup Routes
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
   
    match '/signin' => 'presessions#new', :as => 'signin' 
    match '/preauthenticate' => 'presessions#create', :as => 'preauthentication'
    
    # Catch-all that just loads views from app/views/content/* ...
    # e.g, http://yoursite.com/content/about -> app/views/content/about.html.erb
    #
    match '/content/:action' => 'content'
  end

  root :to => "songs#index"

  devise_for :users

  #
  # Account / User Management Routes
  #
  resources :users
  
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match :billing, :paypal, :plan, :plan_paypal, :cancel
    end
   resources :pages
  end

  # Custom routes specific to our app
  namespace "saas_admin" do
    resources :pages do
      put "reposition", :on => :member
    end
    
    resources :posts
    resources :songs
    resources :messages
  end

  resources :pages, :only => :show
  resources :posts, :only => [ :index, :show ]
  match     "playlist" => "songs#index"
  post      "songs/flag" => "songs#flag",     :as => "flag"

  get    "contact"      => "messages#new",    :as => "contact"
  post   "/home" => "messages#create", :as => "deliver"
  get    "contact/sent" => "messages#sent",   :as => "sent"


end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  
  def page
      @page = Page.find(params[:id])
   end  
   
   def contact
     if request.post? and params[:reset_password]
            if contact = Contact.new(params[:reset_password])

              contact.name = "#{params[:reset_password][:sender_name]}"
              contact.email = "#{params[:reset_password][:sender_email]}"
              contact.subject = "#{params[:reset_password][:title]}"
              contact.message = "#{params[:reset_password][:body]}"
              contact.save


              Emailer.deliver_contact_email(contact)

              flash[:notice] = "Thank you for sending a mail."
              redirect_to("/contacts")

            end
         else
           @title = "contacts"
         end
    
   end
end

app/views/blog/contact.html.erb
<h2><%= @page_title = "Contact" %></h2>

<%= form_for(:message, :url => deliver_url(:subdomain => false)) do |f| %>
  <div class="field string half">
    <%= f.label :sender_name, "Your name" %>
    <%= f.text_field :sender_name %>
  </div>

  <div class="field string half">
    <%= f.label :sender_email, "Your email address" %>
    <%= f.text_field :sender_email %>
  </div>

  <div class="field string gotcha">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field text">
    <%= f.label :body, "Your message" %>
    <%= f.text_area :body, :rows => 8 %>
  </div>

  <div class="buttons">
    <%= f.submit "Send message" %>
  </div>
<% end %>

app/views/blog/page.html.erb
<div class="clear"></div>
<h1><%= @page_title = @page.title %></h1>
<%= @page.body_html.html_safe %>
	

app/views/blog/sent.html.erb
<h2><%= @page_title = "Message Sent" %></h2>

<p>
  Thanks for contacting us! We'll be in touch soon.
</p>