config/routes.rb
class MainSite 
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end

Subscriptions::Application.routes.draw do |map|
  # Routes for the public site
  constraints MainSite do
    # Homepage
    root :to => "content#index"
    map.connect  '/home', :controller=>'home', :action=>'index'
    map.connect '/pages/:id', :controller=>'blog', :action=>'page'
   map.connect '/contacts', :controller=>'blog', :action=>'contact'
   
    # Account Signup Routes
    match '/signup' => 'accounts#plans', :as => 'plans'
    match '/signup/d/:discount' => 'accounts#plans'
    match '/signup/thanks' => 'accounts#thanks', :as => 'thanks'
    match '/signup/create/:discount' => 'accounts#create', :as => 'create', :defaults => { :discount => nil }
    match '/signup/:plan/:discount' => 'accounts#new', :as => 'new_account'
    match '/signup/:plan' => 'accounts#new', :as => 'new_account'
   
    match '/signin' => 'presessions#new', :as => 'signin' 
    match '/preauthenticate' => 'presessions#create', :as => 'preauthentication'
    
    # Catch-all that just loads views from app/views/content/* ...
    # e.g, http://yoursite.com/content/about -> app/views/content/about.html.erb
    #
    match '/content/:action' => 'content'
  end

  root :to => "songs#index"

  devise_for :users

  #
  # Account / User Management Routes
  #
  resources :users
  
  resource :account do 
    member do
      get :dashboard, :thanks, :plans, :canceled
      match :billing, :paypal, :plan, :plan_paypal, :cancel
    end
   resources :pages
  end

  # Custom routes specific to our app
  namespace "saas_admin" do
    resources :pages do
      put "reposition", :on => :member
    end
    
    resources :posts
    resources :songs
    resources :messages
  end

  resources :pages, :only => :show
  resources :posts, :only => [ :index, :show ]
  match     "playlist" => "songs#index"
  post      "songs/flag" => "songs#flag",     :as => "flag"

  get    "contact"      => "messages#new",    :as => "contact"
  post   "/home" => "messages#create", :as => "deliver"
  get    "contact/sent" => "messages#sent",   :as => "sent"


end

app/models/account.rb
class Account < ActiveRecord::Base  
  has_many :users, :dependent => :destroy
  has_many :flags, :dependent => :destroy
  has_many :songs, :through => :flags

  has_one :admin, :class_name => "User", :conditions => { :admin => true }

  accepts_nested_attributes_for :admin

  #
  # Set up the account to own subscriptions. An alternative would be to
  # call 'has_subscription' on the user model, if you only want one user per
  # subscription.  See has_subscription in vendor/plugins/saas/lib/saas.rb
  # for info on how to use the options for implementing limit checking.
  #
  has_subscription :user_limit => Proc.new {|a| a.users.count }

  #
  # The model with "has_subscription" needs to provide an email attribute.
  # But ours is stored in the user model, so we delegate
  #
  delegate :email, :to => :admin
  
  validates_format_of :domain, :with => /\A[a-zA-Z][a-zA-Z0-9]*\Z/
  validates_exclusion_of :domain, :in => %W( support blog www billing help api ), :message => "The domain <strong>{{value}}</strong> is not available."
  validates_presence_of :admin, :on => :create, :message => "information is missing"
  validates_associated :admin, :on => :create
  validate :valid_domain?
  
  attr_accessible :name, :domain, :admin_attributes
  
  acts_as_paranoid
  
  def domain
    @domain ||= self.full_domain.blank? ? '' : self.full_domain.split('.').first
  end
  
  def domain=(domain)
    @domain = domain
    self.full_domain = "#{domain}.#{Saas::Config.base_domain}"
  end
  
  def to_s
    name.blank? ? full_domain : "#{name} (#{full_domain})"
  end

  protected
  
    def valid_domain?
      conditions = new_record? ? ['full_domain = ?', self.full_domain] : ['full_domain = ? and id <> ?', self.full_domain, self.id]
      self.errors.add(:domain, 'is not available') if self.full_domain.blank? || self.class.count(:conditions => conditions) > 0
    end
    
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  inherit_resources
  
  before_filter :authenticate_user!, :except => [ :new, :create, :plans, :canceled, :thanks]
  before_filter :authorized?, :except => [ :new, :create, :plans, :canceled, :thanks]
  before_filter :build_user, :only => [:new, :create]
  before_filter :load_billing, :only => [ :new, :create, :billing, :paypal ]
  before_filter :load_subscription, :only => [ :billing, :plan, :paypal, :plan_paypal ]
  before_filter :load_discount, :only => [ :plans, :plan, :new, :create ]
  before_filter :build_plan, :only => [:new, :create]
  
  # ssl_required :billing, :cancel, :new, :create
  # ssl_allowed :plans, :thanks, :canceled, :paypal
  
  def new
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end
  
  def create
    @account.affiliate = SubscriptionAffiliate.find_by_token(cookies[:affiliate]) unless cookies[:affiliate].blank?

    if @account.needs_payment_info?
      @address.first_name = @creditcard.first_name
      @address.last_name = @creditcard.last_name
      @account.address = @address
      @account.creditcard = @creditcard
    end
    
    if @account.save
      flash[:domain] = @account.domain
      redirect_to thanks_url
    else
      render :action => 'new'#, :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
    end
  end
  
  def update
    if resource.update_attributes(params[:account])
      flash[:notice] = "Your account has been updated."
      redirect_to redirect_url
    else
      render :action => 'edit'
    end
  end
  
  def plans
    @plans = SubscriptionPlan.find(:all, :order => 'amount desc').collect {|p| p.discount = @discount; p }
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end
  
  def billing
    if request.post?
      if params[:paypal].blank?
        @address.first_name = @creditcard.first_name
        @address.last_name = @creditcard.last_name
        if @creditcard.valid? & @address.valid?
          if @subscription.store_card(@creditcard, :billing_address => @address.to_activemerchant, :ip => request.remote_ip)
            flash[:notice] = "Your billing information has been updated."
            redirect_to :action => "billing"
          end
        end
      else
        if redirect_url = @subscription.start_paypal(paypal_account_url, billing_account_url)
          redirect_to redirect_url
        end
      end
    end
  end
  
  # Handle the redirect return from PayPal
  def paypal
    if params[:token]
      if @subscription.complete_paypal(params[:token])
        flash[:notice] = 'Your billing information has been updated'
        redirect_to :action => "billing"
      else
        render :action => 'billing'
      end
    else
      redirect_to :action => "billing"
    end
  end

  def plan
    if request.post?
      @subscription.plan = SubscriptionPlan.find(params[:plan_id])

      # PayPal subscriptions must get redirected to PayPal when
      # changing the plan because a new recurring profile needs
      # to be set up with the new charge amount.
      if @subscription.paypal?
        # Purge the existing payment profile if the selected plan is free
        if @subscription.amount == 0
          logger.info "FREE"
          if @subscription.purge_paypal
            logger.info "PAYPAL"
            flash[:notice] = "Your subscription has been changed."
            SubscriptionNotifier.deliver_plan_changed(@subscription)
          else
            flash[:error] = "Error deleting PayPal profile: #{@subscription.errors.full_messages.to_sentence}"
          end
          redirect_to :action => "plan" and return
        else
          if redirect_url = @subscription.start_paypal(plan_paypal_account_url(:plan_id => params[:plan_id]), plan_account_url)
            redirect_to redirect_url and return
          else
            flash[:error] = @subscription.errors.full_messages.to_sentence
            redirect_to :action => "plan" and return
          end
        end
      end
      
      if @subscription.save
        flash[:notice] = "Your subscription has been changed."
        SubscriptionNotifier.deliver_plan_changed(@subscription)
      else
        flash[:error] = "Error updating your plan: #{@subscription.errors.full_messages.to_sentence}"
      end
      redirect_to :action => "plan"
    else
      @plans = SubscriptionPlan.find(:all, :conditions => ['id <> ?', @subscription.subscription_plan_id], :order => 'amount desc').collect {|p| p.discount = @subscription.discount; p }
    end
  end
  
  # Handle the redirect return from PayPal when changing plans
  def plan_paypal
    if params[:token]
      @subscription.plan = SubscriptionPlan.find(params[:plan_id])
      if @subscription.complete_paypal(params[:token])
        flash[:notice] = "Your subscription has been changed."
        SubscriptionNotifier.deliver_plan_changed(@subscription)
        redirect_to :action => "plan"
      else
        flash[:error] = "Error completing PayPal profile: #{@subscription.errors.full_messages.to_sentence}"
        redirect_to :action => "plan"
      end
    else
      redirect_to :action => "plan"
    end
  end

  def cancel
    if request.post? and !params[:confirm].blank?
      current_account.destroy
      sign_out(:user)
      redirect_to :action => "canceled"
    end
  end
  
  def thanks
    redirect_to :action => "plans" and return unless flash[:domain]
    # render :layout => 'public' # Uncomment if your "public" site has a different layout than the one used for logged-in users
  end
  
  def dashboard
  end

  protected
  
    def resource
      @account ||= current_account
    end
    
    def build_user
      build_resource.admin = User.new unless build_resource.admin
    end
    
    def build_plan
      redirect_to :action => "plans" unless @plan = SubscriptionPlan.find_by_name(params[:plan])
      @plan.discount = @discount
      @account.plan = @plan
    end
    
    def redirect_url
      { :action => 'show' }
    end
    
    def load_billing
      @creditcard = ActiveMerchant::Billing::CreditCard.new(params[:creditcard])
      @address = SubscriptionAddress.new(params[:address])
    end

    def load_subscription
      @subscription = current_account.subscription
    end
    
    # Load the discount by code, but not if it's not available
    def load_discount
      if params[:discount].blank? || !(@discount = SubscriptionDiscount.find_by_code(params[:discount])) || !@discount.available?
        @discount = nil
      end
    end
    
    def authorized?
      redirect_to new_user_session_url unless self.action_name == 'dashboard' || admin?
    end 
    
end

app/views/accounts/billing.html.erb
<h2><%= @page_title = "Billing Information" %></h2>

<% if @subscription.state == "trial" %>
  <% if @subscription.next_renewal_at > Time.now %>
    <p>Thank you for trying <%= Saas::Config.app_name %>!<p>
    <p>Your trial account will expire in <%= pluralize(@subscription.trial_days, "day", "days") %>, at which time you will no longer have access to your account.</p>
    <p>To maintain access to your account, click &#8220;Pay with PayPal&#8221; below. This will send you to PayPal to set up a subscription. When you&#8217;re done, PayPal will send you back to this site.</p>
    <p>Your first charge will happen on <%= @subscription.next_renewal_at.to_s(:long_day) %>.</p>
  <% else %>
    <p>Thank you for trying <%= Saas::Config.app_name %>! Your trial account has expired.<p>
    <p>To regain access to your account, click &#8220;Pay with PayPal&#8221; below. This will send you to PayPal to start your subscription. When you&#8217;re finished, PayPal will send you back to this site.</p>
    <p>Your first charge will happen immediately, and you will be billed monthly thereafter.</p>
  <% end %>
<% end %>

<table>
  <tr>
    <th>Your plan</th>
    <td><%= @subscription.subscription_plan.name %> (<%= link_to "Change plan", plan_account_path %>)</td>
  </tr>

  <% if @subscription.state == "trial" %>
    <tr>
      <th>Trial expiration date</th>
      <td><%= @subscription.next_renewal_at.to_s(:long_day) %></td>
    </tr>
  <% else %>
    <% if @subscription.amount > 0 %>
      <tr>
        <th>Next charge date</th>
        <td><%= @subscription.next_renewal_at.to_s(:long_day) %></td>
      </tr>

      <tr>
        <th>Next charge amount</th>
        <td><%= number_to_currency @subscription.amount %></td>
      </tr>

      <tr>
        <th>Current payment method</th>
        <td>
          <% if @subscription.paypal? %>
            PayPal
          <% elsif @subscription.card_number && @subscription.card_expiration %>
            <%= "#{@subscription.card_number} / #{@subscription.card_expiration}" %>
          <% else %>
            <strong>No payment method entered</strong>
          <% end %>
          </td>
      </tr>
    <% end %>
  <% end %>
</table>

<% if @subscription.amount > 0 %>
  <%= form_for @creditcard, :as => :creditcard, :url => { :action => "billing" } do |f| %>
    <%= render "shared/credit_card_form" %>
    <%= submit_or_cancel "/account", "Pay with PayPal" %>
  <% end %>
<% end %>

app/views/accounts/cancel.html.erb
<h2><%= @page_title = "Cancel Account" %></h2>
<p>You are about to cancel your account. This will <strong>permanently delete all of the data associated with it</strong>.</p>
<p>Once you do this, you will no longer have access to your data, so be sure this is really what you want to do.</p>

<h2>Wait! Before you go...</h2>
<p>
  Instead of canceling your account, perhaps you'd like to just switch your plan.
  <%= link_to "Change your subscription level now", plan_account_path %>.
</p>

<%= form_tag :action => "cancel" do %>
  <div class="field checkbox">
    <input type="checkbox" name="confirm" class="checkbox" value="1" id="really_delete" />
    <label for="really_delete">No thanks, I want to cancel my account and delete all of the data associated with it.</label>
  </div>

  <%= submit_or_cancel "/account", "Delete my account" %>
<% end %>

app/views/accounts/canceled.html.erb
<h2><%= @page_title = "Account Canceled" %></h2>

<p>Your account has been canceled. We're sorry to see you go.</p>
<p>Thanks for checking us out!</p>

app/views/accounts/dashboard.html.erb
<h2>Dashboard</h2>

<ul>
  <li><%= link_to "User Management", users_path %></li>
  <li><%= link_to "Account Management", account_path %></li>
</ul>

app/views/accounts/edit.html.erb
<h2><%= @page_title = "Account Settings" %></h2>

<%= form_for @account, :url => { :action => 'update' }, :html => { :method => :put } do |f| %>
  <%= f.error_messages %>

  <div class="field string">
    <%= f.label :name, "Company name" %>
    <%= f.text_field :name %>
  </div>

  <%= submit_or_cancel :action => 'show' %>
<% end %>

app/views/accounts/new.html.erb
<h2>You're just 60 seconds away from your new XF Playlist account</h2>

<%= form_for @account, :url => { :action => "create" } do |account| %>
  <%= hidden_field_tag "plan", params[:plan] %>
  
  <% if @account.errors.any? %>
    <div class="errorExplanation">
      <h3>Errors encountered with your account information:</h3>
      <ul>
        <%= raw(@account.errors.full_messages.map {|m| content_tag(:li, m)}) %>
      </ul>
    </div>
  <% end %>

  <%= account.fields_for :admin do |admin| %>
    <fieldset>
      <h3>Your information</h3>
      <div class="field string">
        <%= admin.label :name %>
        <%= admin.text_field :name %>
      </div>

      <div class="field string">
        <%= admin.label :email %>
        <%= admin.text_field :email %>
      </div>

      <div class="field string">
        <%= account.label :name, "Company" %>
        <%= account.text_field :name %>
      </div>
    </fieldset>

    <fieldset>
      <h3>Now choose a password</h3>
      <div class="field string">
        <%= admin.label :password %>
        <%= admin.password_field :password %>
      </div>

      <div class="field string">
        <%= admin.label :password_confirmation, "Type your password again to verify" %>
        <%= admin.password_field :password_confirmation %>
      </div>
    </fieldset>
  <% end %>
  
  <fieldset>
    <h3>Pick your new account URL</h3>
    <div class="field string">
      <%= account.text_field :domain %>.<%= Saas::Config.base_domain %>
    </div>
  </fieldset>

  <% if @account.needs_payment_info? %>
    <fieldset>
      <h3>Enter your billing information</h3>

      <%= render :partial => "shared/credit_card_form" %>

      <p>
        Your card will be charged <%= number_to_currency(@account.plan.setup_amount) + " now and " if  @account.plan.setup_amount? && !@account.plan.trial_period? %>
        <%= number_to_currency(@account.plan.amount) %> <%= @account.plan.renewal_period == 1 ? "every month" : "every #{@account.plan.renewal_period} months" %>.
      </p>
    </fieldset>
  <% end %>

  <p>
    <%= account.submit "Create my account" %>
  </p>
<% end %>

app/views/accounts/plan.html.erb
<% if @subscription && @subscription.errors.any? %>
  <div class="errorExplanation">
    <h2>Errors encountered with your change:</h2>
    <ul>
      <%= raw(@subscription.errors.full_messages.map {|m| content_tag(:li, m)}) %>
    </ul>
  </div>
<% end %>

<h2><%= @page_title = "Change Plan" %></h2>
<p>
  You can change your plan level at any time.
</p>
<p>
  The user limits and other features of the new plan that you select will be effective as soon as you make the change,
  but your bill amount will not change until your next bill date.
</p>
<p>
  Your next bill date is <%= @subscription.next_renewal_at.to_s(:long_day) %>.
</p>

<% if @subscription.needs_payment_info? -%>
  <p>
    Please make sure you <%= link_to "enter your billing information", billing_account_url %> before your bill date to prevent an interruption in service.
  </p>
<% end %>

<p>
  You are currently subscribed to the <strong><%= @subscription.subscription_plan.name %> Plan</strong>.
  Please select your desired plan and click the "Change my plan" button.
</p>

<%= form_tag plan_account_url, :id => "choose_new_plan" do %>
  <div class="field select">
    <label for="plan_id">Choose a new plan:</label>
    <select name="plan_id" id="plan_id" onchange="enableButton()">
      <option value=""></option>
      <% @plans.each do |p| %>
        <%= content_tag(:option, p, :value => p.id, :disabled => !current_account.qualifies_for?(p)) %>
      <% end %>
    </select>
  </div>

  <p>
    <input name="commit" type="submit" id="commit" disabled="disabled" value="Change my plan" />
    or <%= link_to "cancel", "/account" %>
  </p>
<% end %>
  
<script type="text/javascript" charset="utf-8">
  function enableButton() {
    document.getElementById('commit').disabled = document.forms[0].elements['plan_id'].selectedIndex == 0
  }
  enableButton();
</script>

app/views/accounts/plans.html.erb
<h2>Plans</h2>

<p>Here are our plans. Pick one:</p>

<ul>
  <%= raw(@plans.map {|p| content_tag(:li, link_to(p, new_account_url(:plan => p, :discount => params[:discount])))}.join) %>
</ul>

app/views/accounts/show.html.erb
<h2><%= @page_title = "Account Management" %></h2>

<ul>
  <li><%= link_to "Switch to a different plan", plan_account_path %></li>
  <li><%= link_to "View or update billing information", billing_account_path %></li>
  <li><%= link_to "Change account settings", edit_account_path %></li>
  <li><%= link_to "Cancel account", cancel_account_path %></li>
</ul>

app/views/accounts/thanks.html.erb
<h2>Account created</h2>

<p>Thank you for signing up!</p>

<p>
  You can log in to your account at
  <a href="http://<%= flash[:domain] %>.<%= Saas::Config.base_domain %>/">http://<%= flash[:domain] %>.<%= Saas::Config.base_domain %>/</a>.
</p>